// ***********************************************************************
// Solution         : FengNiaoWu
// Project          : Credit.Kolibre.Foundation
// File             : Credit.Kolibre.Message.SmsService.EventCode.cs
// Created          : 2017-04-14  9:46
// ***********************************************************************
// <copyright>
//     Copyright © 2016 Kolibre Credit Team. All rights reserved.
// </copyright>
// ***********************************************************************

namespace Credit.Kolibre.Foundation.Logging
{
    public partial class EventCode
    {
        /*
                    70100 - 70199              Credit.Kolibre.Message.SmsService
        */

        // 70100 Credit.Kolibre.Message.SmsService BEGIN
        public const int CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_BASE = CREDIT_KOLIBRE_MESSAGE_BASE + 100;

        public const int CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_SEND_HTTP_REQUEST_FAILED = CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_BASE + 1;
        public const int CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_EXCEPTION_AT_ANALYSIS_RESPONSE = CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_BASE + 2;
        public const int CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_FAILED_STATUS = CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_BASE + 3;
        public const int CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_CAPTCHA_WEBJOB_CREATE_SUCCESS = CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_BASE + 4;
        public const int CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_SMSCAPTCHA_CREATE_SUCCESS = CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_BASE + 5;
        public const int CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_CAPTCHA_WEBJOB_UPDATE_SUCCESS = CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_BASE + 6;
        public const int CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_SMSCAPTCHA_UPDATE_SUCCESS = CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_BASE + 7;
        public const int CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_VERIFY_SMS_ERROR = CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_BASE + 8;
        public const int CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_VERIFY_SMS_EXPIRED = CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_BASE + 9;
        public const int CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_VERIFY_SMS_SUCCESS = CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_BASE + 10;
        public const int CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_INVOKE_SMS_SEND_NOT_SUCCESS_STATUS_CODE = CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_BASE + 11;
        public const int CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_INVOKE_SMS_SEND_FAILED = CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_BASE + 12;
        public const int CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_INVOKE_SMS_VERIFY_NOT_SUCCESS_STATUS_CODE = CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_BASE + 13;
        public const int CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_INVOKE_SMS_VERIFY_FAILED = CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_BASE + 14;
        public const int CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_INVOKE_SMS_VERIFY_TOKEN_DISABLE = CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_BASE + 15;
        public const int CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_INVOKE_SMS_VERIFY_TOKEN_USED = CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_BASE + 16;

        public const int CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_INVOKE_SMS_VERIFY_TOKEN_EXPIRED = CREDIT_KOLIBRE_MESSAGE_SMS_SERVICE_BASE + 17;
        // 70199 Credit.Kolibre.Message.SmsService END
    }
}