// ***********************************************************************
// Solution         : FengNiaoWu
// Project          : Credit.Kolibre.Foundation
// File             : Credit.Kolibre.Apartment.CreditService.EventCode.cs
// Created          : 2017-04-13  20:51
// ***********************************************************************
// <copyright>
//     Copyright © 2016 Kolibre Credit Team. All rights reserved.
// </copyright>
// ***********************************************************************

namespace Credit.Kolibre.Foundation.Logging
{
    public partial class EventCode
    {
        /*
         64000 - 64299               Credit.Kolibre.Apartment.CreditService
         */

        // 64000 Credit.Kolibre.Apartment.CreditService BEGIN
        public const int CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_BASE = CREDIT_KOLIBRE_KOLIBRE_APARTMENT_BASE + 4000;

        public const int CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_VERIFY_FAILED = CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_BASE + 1;
        public const int CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_VERIFY_INVOKE_FAILED = CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_BASE + 2;
        public const int CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_VERIFY_SUCCEEDED = CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_BASE + 3;
        public const int CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_CREATE_REPORT_FAILED = CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_BASE + 4;
        public const int CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_CREATE_REPORT_INVOKE_FAILED = CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_BASE + 5;
        public const int CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_CREATE_REPORT_SUCCEEDED = CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_BASE + 6;
        public const int CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_CREATE_REPORT_BATCH_FAILED = CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_BASE + 7;
        public const int CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_CREATE_REPORT_BATCH_INVOKE_FAILED = CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_BASE + 8;
        public const int CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_SAVE_ACCOUNT_INFO_REPORT_INVOKE_FAILED = CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_BASE + 9;
        public const int CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_FIND_LAST_CREDIT_REPORT_BATCH_INVOKE_FAILED = CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_BASE + 10;
        public const int CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_FIND_LAST_CREDIT_REPORT_BATCH_FAILED = CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_BASE + 11;
        public const int CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_CREATE_CREDIT_AUDIT_RECORD_INVOKE_FAILED = CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_BASE + 12;
        public const int CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_CREATE_CREDIT_AUDIT_RECORD_FAILED = CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_BASE + 13;
        public const int CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_SAVE_ACCOUNT_INFO_REPORT_FAILED = CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_BASE + 14;
        public const int CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_FIND_CREDIT_AUDIT_REPORT_INVOKE_FAILED = CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_BASE + 15;

        public const int CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_FIND_CREDIT_AUDIT_REPORT_FAILED = CREDIT_KOLIBRE_KOLIBRE_APARTMENT_CREDIT_SERVICE_BASE + 16;
        // 64299 Credit.Kolibre.Apartment.CreditService END
    }
}