// ***********************************************************************
// Solution         : FengNiaoWu
// Project          : Credit.Kolibre.Foundation
// File             : ServerEventCode.cs
// Created          : 2017-03-14  16:06
// ***********************************************************************
// <copyright>
//     Copyright © 2016 Kolibre Credit Team. All rights reserved.
// </copyright>
// ***********************************************************************

namespace Credit.Kolibre.Foundation.Logging
{
    public partial class EventCode
    {
        // Server EventCode

        /*
               20000 - 49999                   Credit.Kolibre.Server
                   20000 - 20099               Credit.Kolibre.Server.Dev
                       20000 - 20010           Credit.Kolibre.Server.Dev.Index
                   20100 - 20199               Credit.Kolibre.Server.Utilities
                       20100 - 20140           Credit.Kolibre.Server.Utilities.Files
                   21000 - 21999               Credit.Kolibre.Server.Identities
                   22000 - 39999               Credit.Kolibre.Server.Apartment.Platform
                       22000 - 22099           Credit.Kolibre.Server.Apartment.Platform.HouseAccount
                       22100 - 22199           Credit.Kolibre.Server.Apartment.Platform.HouseAccountInfo
                       22200 - 22299           Credit.Kolibre.Server.Apartment.Platform.HouseInformation
                       22300 - 22399           Credit.Kolibre.Server.Apartment.Platform.LeaseOrder
                       22400 - 22499           Credit.Kolibre.Server.Apartment.Platform.LeaseTransaction
                       22500 - 22599           Credit.Kolibre.Server.Apartment.Platform.Lease
                       22600 - 22699           Credit.Kolibre.Server.Apartment.Platform.Credit 
        */

        // 20000 Credit.Kolibre.Server Credit.Kolibre.Server.Dev Credit.Kolibre.Server.Dev.Index BEGIN
        public const int CREDIT_KOLIBRE_SERVER_BASE = CREDIT_KOLIBRE_BASE + 10000;

        public const int CREDIT_KOLIBRE_SERVER_DEV_BASE = CREDIT_KOLIBRE_SERVER_BASE;

        public const int CREDIT_KOLIBRE_SERVER_DEV_INDEX_BASE = CREDIT_KOLIBRE_SERVER_DEV_BASE;
        // 20010 Credit.Kolibre.Server.Dev.Index END
        // 20099 Credit.Kolibre.Server.Dev END

        // 20100 Credit.Kolibre.Server.Utilities Credit.Kolibre.Server.Utilities.Files BEGIN
        public const int CREDIT_KOLIBRE_SERVER_UTILITIES_BASE = CREDIT_KOLIBRE_SERVER_BASE + 100;

        public const int CREDIT_KOLIBRE_SERVER_UTILITIES_FILES_BASE = CREDIT_KOLIBRE_SERVER_UTILITIES_BASE;
        public const int CREDIT_KOLIBRE_SERVER_UTILITIES_FILES_NOT_SUPPORTED_FORMATE = CREDIT_KOLIBRE_SERVER_UTILITIES_FILES_BASE + 1;

        public const int CREDIT_KOLIBRE_SERVER_UTILITIES_FILES_SIZE_TOO_LARGE = CREDIT_KOLIBRE_SERVER_UTILITIES_FILES_BASE + 2;
        // 20140 Credit.Kolibre.Server.Utilities.Files END

        // 20199 Credit.Kolibre.Server.Utilities END

        // 21000 Credit.Kolibre.Server.Identities BEGIN
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE = CREDIT_KOLIBRE_SERVER_BASE + 1000;

        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_ACCESS_FAILED_ACCOUNT_NOT_EXIST = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 1;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_02 = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 2;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_03 = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 3;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_REGISTER_FAILED = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 4;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_ADD_CLAIM_USER_NOT_EXIST = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 5;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_LOGIN_BY_USER_NAME_LOCKOUT = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 6;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_LOGIN_BY_USER_NAME_NOT_ALLOWED = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 7;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_LOGIN_BY_CELLPHONE_LOCKOUT = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 8;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_LOGIN_BY_CELLPHONE_NOT_ALLOWED = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 9;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_LOGIN_BY_EMAIL_LOCKOUT = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 10;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_LOGIN_BY_EMAIL_NOT_ALLOWED = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 11;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_LOGIN_BY_ID_LOCKOUT = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 12;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_LOGIN_BY_ID_NOT_ALLOWED = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 13;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_REGISTER_CELLPHONE_USED = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 14;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_REGISTER_EMAIL_USED = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 15;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_REGISTER_USER_NAME_USED = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 16;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_CONFIRM_CELLPHONE_USER_WITH_ID_NOT_EXIST = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 17;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_CONFIRM_EMAIL_USER_WITH_ID_NOT_EXIST = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 18;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_LOGIN_BY_CELLPHONE_USER_NOT_EXIST = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 19;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_LOGIN_BY_EMAIL_USER_NOT_EXIST = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 20;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_LOGIN_BY_ID_USER_NOT_EXIST = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 21;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_LOGIN_BY_USER_NAME_USER_NOT_EXIST = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 22;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_23 = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 23;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_24 = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 24;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_ADD_USER_TO_ROLE_USER_NOT_EXIST = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 25;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_ADD_USER_TO_ROLE_ROLE_NOT_EXIST = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 26;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_ADD_CLAIM_TO_ROLE_ROLE_NOT_EXIST = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 27;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_CHANGE_PASSWORD_CAN_NOT_LOAD_USER = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 28;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_CREATE_ROLE_ROLE_ALREADY_EXIST = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 29;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_FIND_BY_CELLPHONE_USER_NOT_EXIST = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 30;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_FIND_BY_EMAIL_USER_NOT_EXIST = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 31;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_FIND_BY_USER_ID_USER_NOT_EXIST = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 32;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_FIND_BY_USER_NAME_USER_NOT_EXIST = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 33;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_INIT_IDENTITY_DUPLICATION_INIT_IDENTITY = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 34;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_35 = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 35;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_CREATE_ROOT_ADMINISTRATOR_IDENTITY_FAILED = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 36;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_RESET_ACCESS_FAILED_COUNT_USER_NOT_EXIST = CREDIT_KOLIBRE_SERVER_BASE + 37;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_SET_PASSWORD_USER_NOT_EXIST = CREDIT_KOLIBRE_SERVER_BASE + 38;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_SET_ROLE_NAME_ROLE_NOT_EXIST = CREDIT_KOLIBRE_SERVER_BASE + 39;
        public const int CREDIT_KOLIBRE_SERVER_IDENTITIES_CHANGE_PASSWORD_OLD_PASSWORD_MISSMATCH = CREDIT_KOLIBRE_SERVER_IDENTITIES_BASE + 40;

        // 21999 Credit.Kolibre.Server.Identities END

        //22000 Credit.Kolibre.Server.Apartment.Platform BEGIN

        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_BASE = CREDIT_KOLIBRE_SERVER_BASE + 2000;

        //22000 Credit.Kolibre.Server.Apartment.Platform.HouseAccount BEGIN
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_BASE;

        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_CELLPHONE_NOT_REGISTER = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 1;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_ACCOUNT_DISABLED = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 2;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_ACCOUNT_LOCKOUT = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 3;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_LOGIN_BY_CELLPHONE_PASSWORD_ERROR = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 4;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_LOGIN_TOKEN_INVALID = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 5;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_LOGIN_TOKEN_USED = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 6;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_CHANGE_PASSWORD_TOKEN_INVALID = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 7;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_CHANGE_PASSWORD_TOKEN_NOT_EXIST = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 8;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_CHANGE_PASSWORD_TOKEN_USED = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 9;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_CHANGE_PASSWORD_FAILED = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 10;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_GET_USER_INFO_FAILED = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 11;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_CANNOT_LOAD_ACCOUNT = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 12;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_CANNOT_ADD_ACCOUNT_INFO_REPEATED = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 13;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_GET_BY_CELLPHONE_NOT_EXIST = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 14;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_SEND_SMS_CELLPHONE_USED = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 15;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_SEND_SMS_CELLPHONE_NOT_USED = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 16;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_SEND_SMS_ACCOUNT_NOT_ENABLED = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 17;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_SEND_SMS_ACCOUNT_LOCKEDE = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 18;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_ID_CARD_NO_INVALID = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 19;

        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_NOT_REGISTER = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_BASE + 20;
        //22099 Credit.Kolibre.Server.Apartment.Platform.HouseAccount END

        //22100 Credit.Kolibre.Server.Apartment.Platform.HouseAccountInfo BEGIN
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_INFO_BASE = CREDIT_KOLIBRE_SERVER_BASE + 2100;

        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_INFO_UPDATE_FAILED = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_INFO_BASE + 1;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_INFO_NOT_EXIST = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_INFO_BASE + 2;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_INFO_NOT_VERIFIED = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_INFO_BASE + 3;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_INFO_EXTENSION_INFO_NOT_EXIST = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_INFO_BASE + 4;

        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_INFO_APARTMENT_STORAGED_FAILED = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_ACCOUNT_INFO_BASE + 5;
        //22199 Credit.Kolibre.Server.Apartment.Platform.HouseAccountInfo END

        //22200 Credit.Kolibre.Server.Apartment.Platform.HouseInformation BEGIN

        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_INFORMATION_BASE = CREDIT_KOLIBRE_SERVER_BASE + 2200;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_INFORMATION_INVALID_FLOOR = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_INFORMATION_BASE + 1;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_INFORMATION_ALREADY_EXIST = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_INFORMATION_BASE + 2;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_INFORMATION_HOUSE_ID_IS_NOT_GUID = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_HOUSE_INFORMATION_BASE + 3;

        //22299 Credit.Kolibre.Server.Apartment.Platform.HouseInformation END

        //22300 Credit.Kolibre.Server.Apartment.Platform.LeaseOrder BEGIN

        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_ORDER_BASE = CREDIT_KOLIBRE_SERVER_BASE + 2300;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_ORDER_LEASE_ORDER_NOT_EXIST = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_ORDER_BASE + 1;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_ORDER_UPDATE_ORDER_STATE_VERIFIED_FAILED = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_ORDER_BASE + 2;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_ORDER_FIND_ALL_LEASEORDER_INVALID_ORDERSTATE = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_ORDER_BASE + 3;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_ORDER_LEASE_ORDER_ID_IS_NOT_GUID = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_ORDER_BASE + 4;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_ORDER_LEASE_ORDER_LEASEID_NOT_EXIST = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_ORDER_BASE + 5;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_ORDER_LEASE_ORDER_STAGING_ORDER_EXIST = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_ORDER_BASE + 6;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_ORDER_FIND_LEASE_ORDER_FAILED = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_ORDER_BASE + 7;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_ORDER_ACCOUNT_ID_IS_NOT_EXIST = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_ORDER_BASE + 8;

        //22399 Credit.Kolibre.Server.Apartment.Platform.LeaseOrder END

        //22400 Credit.Kolibre.Server.Apartment.Platform.LeaseTransaction BEGIN

        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_TRANSACTION_BASE = CREDIT_KOLIBRE_SERVER_BASE + 2400;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_TRANSACTION_TRANSACTION_NOT_EXIST = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_TRANSACTION_BASE + 1;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_TRANSACTION_LEASEORDER_NOT_EXIST = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_TRANSACTION_BASE + 2;

        //22499 Credit.Kolibre.Server.Apartment.Platform.LeaseTransaction END

        //22500 Credit.Kolibre.Server.Apartment.Platform.Lease BEGIN
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_BASE = CREDIT_KOLIBRE_SERVER_BASE + 2500;

        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_CREATELEASEFAILED = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_BASE + 1;

        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASEID_IS_NOT_GUID = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_LEASE_BASE + 2;
        //22599 Credit.Kolibre.Server.Apartment.Platform.Lease END 

        //22600 Credit.Kolibre.Server.Apartment.Platform.Credit BEGIN
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_CREDIT_BASE = CREDIT_KOLIBRE_SERVER_BASE + 2600;

        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_CREDIT_CREATE_REPORT_FAILED = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_CREDIT_BASE + 1;
        public const int CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_CREDIT_CREATE_REPORT_BATCH_FAILED = CREDIT_KOLIBRE_SERVER_KOLIBRE_APARTMENT_CREDIT_BASE + 2;

        //22699 Credit.Kolibre.Server.Apartment.Platform.Credit END 

        //39999 Credit.Kolibre.Server.Apartment.Platform END

        // 49999 Credit.Kolibre.Server END
    }
}